2023-06-02 11:32:50,482 - ERROR - Traceback (most recent call last):
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/system_test.py", line 31, in test_system
    data = aquirer.get(
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 161, in get
    data = self._request(pair, minutes, start, end)
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 78, in _request
    raise ConnectionError(response)
ConnectionError: {'status': 'ERROR', 'request_id': '99265e9b71f6afd931bb6440021b43e1', 'error': 'Unknown API Key'}

2023-06-02 11:32:50,830 - ERROR - Traceback (most recent call last):
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/system_test.py", line 31, in test_system
    data = aquirer.get(
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 161, in get
    data = self._request(pair, minutes, start, end)
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 78, in _request
    raise ConnectionError(response)
ConnectionError: {'status': 'ERROR', 'request_id': 'ef0991744126d863f8a9e7b06a10175c', 'error': 'Unknown API Key'}

2023-06-02 11:32:51,179 - ERROR - Traceback (most recent call last):
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/system_test.py", line 31, in test_system
    data = aquirer.get(
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 161, in get
    data = self._request(pair, minutes, start, end)
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 78, in _request
    raise ConnectionError(response)
ConnectionError: {'status': 'ERROR', 'request_id': '90f92cdac53aad0ecdedee57e1786202', 'error': 'Unknown API Key'}

2023-06-02 11:32:51,538 - ERROR - Traceback (most recent call last):
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/system_test.py", line 31, in test_system
    data = aquirer.get(
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 161, in get
    data = self._request(pair, minutes, start, end)
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 78, in _request
    raise ConnectionError(response)
ConnectionError: {'status': 'ERROR', 'request_id': 'eeeda1ac09634c0dfd0c1b66a38db815', 'error': 'Unknown API Key'}

2023-06-02 11:32:51,888 - ERROR - Traceback (most recent call last):
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/system_test.py", line 31, in test_system
    data = aquirer.get(
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 161, in get
    data = self._request(pair, minutes, start, end)
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 78, in _request
    raise ConnectionError(response)
ConnectionError: {'status': 'ERROR', 'request_id': 'ab93b26c3b0b0dc2f2343c2f8c943962', 'error': 'Unknown API Key'}

2023-06-02 11:32:52,390 - ERROR - Traceback (most recent call last):
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/system_test.py", line 31, in test_system
    data = aquirer.get(
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 161, in get
    data = self._request(pair, minutes, start, end)
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 78, in _request
    raise ConnectionError(response)
ConnectionError: {'status': 'ERROR', 'request_id': '2b305fe8e3038e95f42bccbd44fc4558', 'error': 'Unknown API Key'}

2023-06-02 11:32:52,747 - ERROR - Traceback (most recent call last):
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/system_test.py", line 31, in test_system
    data = aquirer.get(
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 161, in get
    data = self._request(pair, minutes, start, end)
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 78, in _request
    raise ConnectionError(response)
ConnectionError: {'status': 'ERROR', 'request_id': '172034f1e605978be351eb00e8cfcc71', 'error': 'Unknown API Key'}

2023-06-02 11:32:53,179 - ERROR - Traceback (most recent call last):
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/system_test.py", line 31, in test_system
    data = aquirer.get(
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 161, in get
    data = self._request(pair, minutes, start, end)
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 78, in _request
    raise ConnectionError(response)
ConnectionError: {'status': 'ERROR', 'request_id': '5a47513791d9d89a484947e70d0edadb', 'error': 'Unknown API Key'}

2023-06-02 11:32:53,532 - ERROR - Traceback (most recent call last):
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/system_test.py", line 31, in test_system
    data = aquirer.get(
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 161, in get
    data = self._request(pair, minutes, start, end)
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 78, in _request
    raise ConnectionError(response)
ConnectionError: {'status': 'ERROR', 'request_id': 'ab5a2070360e7c5c9a6ab731c6dd3bb1', 'error': 'Unknown API Key'}

2023-06-02 11:32:53,886 - ERROR - Traceback (most recent call last):
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/system_test.py", line 31, in test_system
    data = aquirer.get(
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 161, in get
    data = self._request(pair, minutes, start, end)
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 78, in _request
    raise ConnectionError(response)
ConnectionError: {'status': 'ERROR', 'request_id': '002c2c09779c2ec10e489a62ca82ddd4', 'error': 'Unknown API Key'}

2023-06-02 11:32:54,305 - ERROR - Traceback (most recent call last):
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/system_test.py", line 31, in test_system
    data = aquirer.get(
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 161, in get
    data = self._request(pair, minutes, start, end)
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 78, in _request
    raise ConnectionError(response)
ConnectionError: {'status': 'ERROR', 'request_id': '62ba82ccf3e27a5c2891ce8f46884592', 'error': 'Unknown API Key'}

2023-06-02 11:32:54,657 - ERROR - Traceback (most recent call last):
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/system_test.py", line 31, in test_system
    data = aquirer.get(
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 161, in get
    data = self._request(pair, minutes, start, end)
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 78, in _request
    raise ConnectionError(response)
ConnectionError: {'status': 'ERROR', 'request_id': 'ae550d2879361b668d432dbfda97ac2e', 'error': 'Unknown API Key'}

2023-06-02 11:32:55,245 - ERROR - Traceback (most recent call last):
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/system_test.py", line 31, in test_system
    data = aquirer.get(
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 161, in get
    data = self._request(pair, minutes, start, end)
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 78, in _request
    raise ConnectionError(response)
ConnectionError: {'status': 'ERROR', 'request_id': '249cf12434b72f8a6d84d8de05bffb8e', 'error': 'Unknown API Key'}

2023-06-02 11:32:55,636 - ERROR - Traceback (most recent call last):
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/system_test.py", line 31, in test_system
    data = aquirer.get(
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 161, in get
    data = self._request(pair, minutes, start, end)
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 78, in _request
    raise ConnectionError(response)
ConnectionError: {'status': 'ERROR', 'request_id': '09d9d05848b22236bb7b03985edff342', 'error': 'Unknown API Key'}

2023-06-02 11:32:55,987 - ERROR - Traceback (most recent call last):
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/system_test.py", line 31, in test_system
    data = aquirer.get(
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 161, in get
    data = self._request(pair, minutes, start, end)
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 78, in _request
    raise ConnectionError(response)
ConnectionError: {'status': 'ERROR', 'request_id': 'abcdf5e789cbd653320780934209a815', 'error': 'Unknown API Key'}

2023-06-02 11:32:56,399 - ERROR - Traceback (most recent call last):
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/system_test.py", line 31, in test_system
    data = aquirer.get(
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 161, in get
    data = self._request(pair, minutes, start, end)
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 78, in _request
    raise ConnectionError(response)
ConnectionError: {'status': 'ERROR', 'request_id': '971f6282aff676fcf2dd9dcba210180e', 'error': 'Unknown API Key'}

2023-06-02 11:32:56,758 - ERROR - Traceback (most recent call last):
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/system_test.py", line 31, in test_system
    data = aquirer.get(
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 161, in get
    data = self._request(pair, minutes, start, end)
  File "/Users/FabianFranz/Development/Projects/forex-predicter/test/../src/data_aquirer.py", line 78, in _request
    raise ConnectionError(response)
ConnectionError: {'status': 'ERROR', 'request_id': 'e169d330ede04c9c1e1a67db12673bac', 'error': 'Unknown API Key'}

